/**
 * Created by nitesh on 12-07-2015.
 */
var lov={
  "location":[
      {"id":1,"name":"Ahmedabad"},
      {"id":2,"name":"Bangalore"},
      {"id":3,"name":"Chandigarh"},
      {"id":4,"name":"Chennai"},
      {"id":5,"name":"Delhi"},
      {"id":6,"name":"Gurgaon"},
      {"id":7,"name":"Hyderabad"},
      {"id":8,"name":"Kolkata"},
      {"id":9,"name":"Mumbai"},
      {"id":10,"name":"Noida"},
      {"id":11,"name":"Pune"},
      {"id":12,"name":"Guntur"},
      {"id":13,"name":"Kakinada"},
      {"id":14,"name":"Kurnool"},
      {"id":15,"name":"Nellore"},
      {"id":16,"name":"Nizamabad"},
      {"id":17,"name":"Rajamundry"},
      {"id":18,"name":"Tirupati"},
      {"id":19,"name":"Vijayawada"},
      {"id":20,"name":"Visakhapatnam"},
      {"id":21,"name":"Warangal"},
      {"id":22,"name":"Anantapur"},
      {"id":23,"name":"Guntakal"},
      {"id":24,"name":"Hyderabad"},
      {"id":25,"name":"Rajahmundry"},
      {"id":26,"name":"Secunderabad"},
      {"id":27,"name":"Andhra Pradesh - Other"},
      {"id":28,"name":"Itanagar"},
      {"id":29,"name":"Arunachal Pradesh - Other"},
      {"id":30,"name":"Dispur"},
      {"id":31,"name":"Guwahati"},
      {"id":32,"name":"Silchar"},
      {"id":33,"name":"Assam - Other"},
      {"id":34,"name":"Bhilaigarh"},
      {"id":35,"name":"Patna"},
      {"id":36,"name":"Bihar - Other"},
      {"id":37,"name":"Bhagalpur"},
      {"id":38,"name":"Bilaspur"},
      {"id":39,"name":"Raipur"},
      {"id":40,"name":"Bhillai"},
      {"id":41,"name":"Chhattisgarh - Other"},
      {"id":42,"name":"Goa"},
      {"id":43,"name":"Panaji"},
      {"id":44,"name":"Panjim"},
      {"id":45,"name":"Vasco Da Gama"},
      {"id":46,"name":"Goa - Other"},
      {"id":47,"name":"Anand"},
      {"id":48,"name":"Ankleshwar"},
      {"id":49,"name":"Baroda"},
      {"id":50,"name":"Bharuch"},
      {"id":51,"name":"Bhavnagar"},
      {"id":52,"name":"Bhuj"},
      {"id":53,"name":"Gandhinagar"},
      {"id":54,"name":"Jamnagar"},
      {"id":55,"name":"Kandla"},
      {"id":56,"name":"Porbandar"},
      {"id":57,"name":"Rajkot"},
      {"id":58,"name":"Surat"},
      {"id":59,"name":"Vadodara"},
      {"id":60,"name":"Valsad"},
      {"id":61,"name":"Vapi"},
      {"id":62,"name":"Ahmedabad"},
      {"id":63,"name":"Gir"},
      {"id":64,"name":"Gujarat - Other"},
      {"id":65,"name":"Ambala"},
      {"id":66,"name":"Faridabad"},
      {"id":67,"name":"Hisar"},
      {"id":68,"name":"Karnal"},
      {"id":69,"name":"Kurukshetra"},
      {"id":70,"name":"Panipat"},
      {"id":71,"name":"Rohtak"},
      {"id":72,"name":"Sonipat / Sonepat"},
      {"id":73,"name":"Yamunanagar"},
      {"id":74,"name":"Chandigarh"},
      {"id":75,"name":"Gurgaon"},
      {"id":76,"name":"Haryana - Other"},
      {"id":77,"name":"Baddi"},
      {"id":78,"name":"Dalhousie"},
      {"id":79,"name":"Dharamsala"},
      {"id":80,"name":"Kulu/Manali"},
      {"id":81,"name":"Shimla"},
      {"id":82,"name":"Himachal Pradesh - Other"},
      {"id":83,"name":"Jammu"},
      {"id":84,"name":"Srinagar"},
      {"id":85,"name":"Jammu & Kashmir - Other"},
      {"id":86,"name":"Bokaro"},
      {"id":87,"name":"Dhanbad"},
      {"id":88,"name":"Jamshedpur"},
      {"id":89,"name":"Ranchi"},
      {"id":90,"name":"Jharkhand - Other"},
      {"id":91,"name":"Bengaluru / Bangalore"},
      {"id":92,"name":"Belgaum"},
      {"id":93,"name":"Bellary"},
      {"id":94,"name":"Bidar"},
      {"id":95,"name":"Dharwad"},
      {"id":96,"name":"Gulbarga"},
      {"id":97,"name":"Hubli"},
      {"id":98,"name":"Kolar"},
      {"id":99,"name":"Mangalore"},
      {"id":100,"name":"Mysore"},
      {"id":101,"name":"Shimoga"},
      {"id":102,"name":"Karnataka - Other"},
      {"id":103,"name":"Alappuzha / Alleppey"},
      {"id":104,"name":"Cochin / Kochi / Ernakulam"},
      {"id":105,"name":"Idukki"},
      {"id":106,"name":"Kannur"},
      {"id":107,"name":"Kasargod"},
      {"id":108,"name":"Kollam"},
      {"id":109,"name":"Kottayam"},
      {"id":110,"name":"Kozhikode / Calicut"},
      {"id":111,"name":"Malappuram"},
      {"id":112,"name":"Pallakad"},
      {"id":113,"name":"Pathanamthitta"},
      {"id":114,"name":"Thrissur / Trissur"},
      {"id":115,"name":"Thiruvananthapuram / Trivandrum"},
      {"id":116,"name":"Wayanad"},
      {"id":117,"name":"Palakkad"},
      {"id":118,"name":"Palghat"},
      {"id":119,"name":"Kerala - Other"},
      {"id":120,"name":"Bhopal"},
      {"id":121,"name":"Gwalior"},
      {"id":122,"name":"Indore"},
      {"id":123,"name":"Jabalpur"},
      {"id":124,"name":"Ujjain"},
      {"id":125,"name":"Madhya Pradesh - Other"},
      {"id":126,"name":"Ahmednagar"},
      {"id":127,"name":"Aurangabad"},
      {"id":128,"name":"Jalgaon"},
      {"id":129,"name":"Kolhapur"},
      {"id":130,"name":"Nagpur"},
      {"id":131,"name":"Nasik"},
      {"id":132,"name":"Sholapur"},
      {"id":133,"name":"Mumbai"},
      {"id":134,"name":"Mumbai Suburbs"},
      {"id":135,"name":"Navi Mumbai"},
      {"id":136,"name":"Pune"},
      {"id":137,"name":"Solapur"},
      {"id":138,"name":"Maharashtra - Other"},
      {"id":139,"name":"Imphal"},
      {"id":140,"name":"Manipur - Other"},
      {"id":141,"name":"Shillong"},
      {"id":142,"name":"Meghalaya - Other"},
      {"id":143,"name":"Aizawal"},
      {"id":144,"name":"Mizoram - Other"},
      {"id":145,"name":"Kohima"},
      {"id":146,"name":"Dimapur"},
      {"id":147,"name":"Nagaland - Other"},
      {"id":148,"name":"Bhubaneshwar"},
      {"id":149,"name":"Cuttack"},
      {"id":150,"name":"Paradeep"},
      {"id":151,"name":"Puri"},
      {"id":152,"name":"Rourkela"},
      {"id":153,"name":"Orissa - Other"},
      {"id":154,"name":"Amritsar"},
      {"id":155,"name":"Bhatinda"},
      {"id":156,"name":"Jalandhar"},
      {"id":157,"name":"Ludhiana"},
      {"id":158,"name":"Mohali"},
      {"id":159,"name":"Pathankot"},
      {"id":160,"name":"Patiala"},
      {"id":161,"name":"Bathinda"},
      {"id":162,"name":"Chandigarh"},
      {"id":163,"name":"Punjab - Other"},
      {"id":164,"name":"Ajmer"},
      {"id":165,"name":"Jaipur"},
      {"id":166,"name":"Jaisalmer"},
      {"id":167,"name":"Jodhpur"},
      {"id":168,"name":"Kota"},
      {"id":169,"name":"Udaipur"},
      {"id":170,"name":"Rajasthan - Other"},
      {"id":171,"name":"Gangtok"},
      {"id":172,"name":"Sikkim - Other"},
      {"id":173,"name":"Coimbatore"},
      {"id":174,"name":"Erode"},
      {"id":175,"name":"Hosur"},
      {"id":176,"name":"Madurai"},
      {"id":177,"name":"Nagercoil"},
      {"id":178,"name":"Ooty"},
      {"id":179,"name":"Salem"},
      {"id":180,"name":"Thanjavur"},
      {"id":181,"name":"Tirunalveli"},
      {"id":182,"name":"Trichy"},
      {"id":183,"name":"Tuticorin"},
      {"id":184,"name":"Vellore"},
      {"id":185,"name":"Chennai"},
      {"id":186,"name":"Cuddalore"},
      {"id":187,"name":"Tamil Nadu - Other"},
      {"id":188,"name":"Agartala"},
      {"id":189,"name":"Tripura - Other"},
      {"id":190,"name":"Daman"},
      {"id":191,"name":"Kavaratti"},
      {"id":192,"name":"Pondicherry"},
      {"id":193,"name":"Port Blair"},
      {"id":194,"name":"Silvassa"},
      {"id":195,"name":"Chandigarh"},
      {"id":196,"name":"Dadra & Nagar Haveli"},
      {"id":197,"name":"Delhi"},
      {"id":198,"name":"Agra"},
      {"id":199,"name":"Aligarh"},
      {"id":200,"name":"Allahabad"},
      {"id":201,"name":"Bareilly"},
      {"id":202,"name":"Faizabad"},
      {"id":203,"name":"Ghaziabad"},
      {"id":204,"name":"Gorakhpur"},
      {"id":205,"name":"Kanpur"},
      {"id":206,"name":"Lucknow"},
      {"id":207,"name":"Mathura"},
      {"id":208,"name":"Meerut"},
      {"id":209,"name":"Moradabad"},
      {"id":210,"name":"Varanasi"},
      {"id":211,"name":"Noida"},
      {"id":212,"name":"Uttar Pradesh - Other"},
      {"id":213,"name":"Dehradun"},
      {"id":214,"name":"Roorkee"},
      {"id":215,"name":"Uttaranchal - Other"},
      {"id":216,"name":"Asansol"},
      {"id":217,"name":"Durgapur"},
      {"id":218,"name":"Haldia"},
      {"id":219,"name":"Kharagpur"},
      {"id":220,"name":"Siliguri"},
      {"id":221,"name":"Kolkata"},
      {"id":222,"name":"West Bengal - Other"},
      {"id":223,"name":"OTHERS"},

  ],


    "notice_period":[
        {"id":1,"name":"Immediately Available"},
        {"id":2,"name":"1 month"},
        {"id":3,"name":"2 months"},
        {"id":4,"name":"3 months"},
        {"id":5,"name":"More than 3 Months"},

    ],
    "referrer":[
        {"id":1,"name":"Hiring Manager (If you would be directly involved in hiring process)"},
        {"id":2,"name":"Team Hiring (You would share CV directly with hiring Manager)"},
        {"id":3,"name":"General Referral (You would upload CV in referral portal or Give to HR)"},
        {"id":4,"name":"Human Resources (You are part of HR team hiring for this position)"},
        {"id":5,"name":"Others"},

    ],
    "qualification":[

        {"id":1,"name":"B.Sc"},
        {"id":2,"name":"B.Com"},
        {"id":3,"name":"Diploma"},
        {"id":4,"name":"B.TECH/B.E."},
        {"id":5,"name":"B.A."},
        {"id":6,"name":"B.B.A"},
        {"id":7,"name":"B.H.M"},
        {"id":8,"name":"B.Pharma"},
        {"id":9,"name":"B.C.A."},
        {"id":10,"name":"LLB/LLM"},
        {"id":11,"name":"CA"},
        {"id":12,"name":"CS"},
        {"id":13,"name":"ICWA"},
        {"id":14,"name":"M.B.B.S"},
        {"id":15,"name":"M.Com"},
        {"id":16,"name":"M.A."},
        {"id":17,"name":"MBA/PGDM"},
        {"id":18,"name":"MCA"},
        {"id":19,"name":"M.Tech"},
        {"id":20,"name":"M.Sc."},
        {"id":21,"name":"M.S."},
        {"id":22,"name":"M.D."},
        {"id":23,"name":"OTHERS"},

    ],
    "salary range":[

        {"id":2,"name":"<5"},
        {"id":3,"name":"6"},
        {"id":4,"name":"7"},
        {"id":5,"name":"8"},
        {"id":6,"name":"9"},
        {"id":7,"name":"10"},
        {"id":8,"name":"11"},
        {"id":9,"name":"12"},
        {"id":10,"name":"13"},
        {"id":11,"name":"14"},
        {"id":12,"name":"15"},
        {"id":13,"name":"16"},
        {"id":14,"name":"17"},
        {"id":15,"name":"18"},
        {"id":16,"name":"19"},
        {"id":17,"name":"20"},
        {"id":18,"name":"22"},
        {"id":19,"name":"24"},
        {"id":20,"name":"26"},
        {"id":21,"name":"28"},
        {"id":22,"name":"30"},
        {"id":23,"name":"33"},
        {"id":24,"name":"36"},
        {"id":25,"name":"40"},
        {"id":26,"name":"45"},
        {"id":27,"name":"50"},
        {"id":28,"name":">50"},

],
"industries":[
    {"id":2,"name":"Advertising/PR/Events"},
    {"id":3,"name":"Automotive/ Ancillaries"},
    {"id":4,"name":"Banking/ Financial Services"},
    {"id":5,"name":"Bio Technology & Life Sciences"},
    {"id":6,"name":"Chemicals/Petrochemicals"},
    {"id":7,"name":"Construction"},
    {"id":8,"name":"FMCG"},
    {"id":9,"name":"Courier/ Freight/ Transportation"},
    {"id":10,"name":"Education"},
    {"id":11,"name":"E-Learning"},
    {"id":12,"name":"Engineering, Procurement, Construction"},
    {"id":13,"name":"Entertainment/ Media/ Publishing"},
    {"id":14,"name":"Food & Packaged Food"},
    {"id":15,"name":"Hospitals/ Health Care"},
    {"id":16,"name":"Hotels/ Restaurant"},
    {"id":17,"name":"Insurance"},
    {"id":18,"name":"IT/ Computers - Hardware"},
    {"id":19,"name":"IT/ Computers - Software"},
    {"id":20,"name":"ITES/BPO"},
    {"id":21,"name":"KPO/Analytics"},
    {"id":22,"name":"Machinery/ Equipment Mfg."},
    {"id":23,"name":"Oil/ Gas/ Petroleum"},
    {"id":24,"name":"Pharmaceuticals"},
    {"id":25,"name":"Public Relations (PR)"},
    {"id":26,"name":"Real Estate"},
    {"id":27,"name":"Retailing"},
    {"id":28,"name":"Shipping/ Marine Services"},
    {"id":29,"name":"Telecom"},
    {"id":30,"name":"Travel/ Tourism"},
    {"id":31,"name":"Plastic/ Rubber"},
    {"id":32,"name":"Power/Energy"},
    {"id":33,"name":"Agriculture/ Dairy Based"},
    {"id":34,"name":"Aviation/Aerospace"},
    {"id":35,"name":"Beauty/Fitness/PersonalCare/SPA"},
    {"id":36,"name":"Beverages/ Liquor"},
    {"id":37,"name":"Cement"},
    {"id":38,"name":"Ceramics & Sanitary Ware"},
    {"id":39,"name":"Consultancy"},
    {"id":40,"name":"Dotcom"},
    {"id":41,"name":"Electrical/Switchgear"},
    {"id":42,"name":"Environmental Service"},
    {"id":43,"name":"Facility management"},
    {"id":44,"name":"Fertilizer/ Pesticides"},
    {"id":45,"name":"Textiles / Yarn / Fabrics / Garments"},
    {"id":46,"name":"Gems & Jewellery"},
    {"id":47,"name":"Government/ PSU/ Defence"},
    {"id":48,"name":"Consumer Electronics/Appliances"},
    {"id":49,"name":"Iron/ Steel"},
    {"id":50,"name":"ISP"},
    {"id":51,"name":"Law Enforcement/Security Services"},
    {"id":52,"name":"Leather"},
    {"id":53,"name":"Market Research"},
    {"id":54,"name":"Medical Transcription"},
    {"id":55,"name":"Mining"},
    {"id":56,"name":"NGO"},
    {"id":57,"name":"Non-Ferrous Metals (Aluminium, Zinc etc.)"},
    {"id":58,"name":"Office Equipment/Automation"},
    {"id":59,"name":"Paints"},
    {"id":60,"name":"Paper"},
    {"id":61,"name":"Printing/ Packaging"},
    {"id":62,"name":"Semiconductor"},
    {"id":63,"name":"Social Media"},
    {"id":64,"name":"Sugar"},
    {"id":65,"name":"Tyres"},
    {"id":66,"name":"Wood"},
    {"id":67,"name":"Others"},

],

    "certifications":[
        {"id":1,"name":"CFA (Int)"},
        {"id":2,"name":"CFA (India)"},
        {"id":3,"name":"FRM"},
        {"id":4,"name":"PRM"},
        {"id":5,"name":"CMA"},
        {"id":6,"name":"CA"},
        {"id":7,"name":"CS"},
        {"id":8,"name":"ICWAI"},
        {"id":9,"name":"PRM"},
        {"id":10,"name":"Others"},

    ],

    "institutes":[
        {"id":1,"name":"Agra University"},
        {"id":2,"name":"Air Hostess Academy (AHA)"},
        {"id":3,"name":"Alagappa University"},
        {"id":4,"name":"Aligarh Muslim University (AMU)"},
        {"id":5,"name":"All India Institute of Management Studies"},
        {"id":6,"name":"All India Institute of Medical Sciences (AIIMS), Delhi"},
        {"id":7,"name":"All India Management Association (AIMA)"},
        {"id":8,"name":"Allahabad University"},
        {"id":9,"name":"Alliance Business Academy (ABA)"},
        {"id":10,"name":"Amity Business School (ABS)"},
        {"id":11,"name":"Amity Law School, Noida"},
        {"id":12,"name":"Amity School of Fashion Technology, Noida"},
        {"id":13,"name":"Amity University"},
        {"id":14,"name":"Amravati University"},
        {"id":15,"name":"Amrita Institute of Medical Sciences & Research Centre, Kochi"},
        {"id":16,"name":"Andhra University"},
        {"id":17,"name":"Anna University"},
        {"id":18,"name":"Annamalai University"},
        {"id":19,"name":"Apeejay School Of Marketing (ASM)"},
        {"id":20,"name":"Aptech"},
        {"id":21,"name":"Arena Multimedia"},
        {"id":22,"name":"Armed Forces Medical College (AFMC), Pune"},
        {"id":23,"name":"Asansol Engineering College (AEC)"},
        {"id":24,"name":"Asia Pacific Institute of Management (APIM)"},
        {"id":25,"name":"Assam Engineering College (AEC)"},
        {"id":26,"name":"Assam University"},
        {"id":27,"name":"Avadh University"},
        {"id":28,"name":"B J Medical College, Pune"},
        {"id":29,"name":"B N Mandal University (BNMU)"},
        {"id":30,"name":"Babasaheb Ambedkar Marathwada University (BAMU), Aurangabad"},
        {"id":31,"name":"Babasaheb Bhimrao Ambedkar University (BBAU), Lucknow"},
        {"id":32,"name":"Banaras Hindu University (BHU), Varanasi"},
        {"id":33,"name":"Banasthali University"},
        {"id":34,"name":"Bangalore Institute Of Technology (BIT)"},
        {"id":35,"name":"Bangalore Medical College (BMC)"},
        {"id":36,"name":"Bangalore University"},
        {"id":37,"name":"Barkatullah University"},
        {"id":38,"name":"Bengal Engineering College (BEC)"},
        {"id":39,"name":"Berhampur University"},
        {"id":40,"name":"Bhagalpur University"},
        {"id":41,"name":"Bharathidasan University, Trichy"},
        {"id":42,"name":"Bharatiya Vidya Bhavan (BVB)"},
        {"id":43,"name":"Bhartiyar University, Coimbatore"},
        {"id":44,"name":"Bhavnagar University"},
        {"id":45,"name":"Bhopal University"},
        {"id":46,"name":"Bihar University"},
        {"id":47,"name":"Biju Patnaik University of Technology (BPUT)"},
        {"id":48,"name":"Bikaner University"},
        {"id":49,"name":"Birla Institute of Management Technology (BIMT)"},
        {"id":50,"name":"Birla Institute of Technology (BIT), Ranchi"},
        {"id":51,"name":"Birla Institute of Technology and Science (BITS), Pilani"},
        {"id":52,"name":"Board of Technical Education (BTE)"},
        {"id":53,"name":"Bundelkhand University"},
        {"id":54,"name":"Burdwan University"},
        {"id":55,"name":"CIPET"},
        {"id":56,"name":"Calcutta Medical College (CMC)"},
        {"id":57,"name":"Calcutta University"},
        {"id":58,"name":"Calicut University"},
        {"id":59,"name":"Centre for Development of Advanced Computing (CDAC)"},
        {"id":60,"name":"Ch Charan Singh University (CCSU), Meerut"},
        {"id":61,"name":"Chandigarh College of Architecture, Chandigarh"},
        {"id":62,"name":"Chennai University"},
        {"id":63,"name":"Chhatrapati Shahu Ji Maharaj University (CSJMU)"},
        {"id":64,"name":"Christ College, Bangalore"},
        {"id":65,"name":"Christian College, Lucknow"},
        {"id":66,"name":"Christian Medical College (CMC), Vellore"},
        {"id":67,"name":"Christian Medical College(CMC, Ludhiana), Ludhiana"},
        {"id":68,"name":"Cochin University of Science and Technology (CUST)"},
        {"id":69,"name":"College of Engineering and Technology (CET), Bhubaneshwar"},
        {"id":70,"name":"College of Engineering, Anna University, Guindy"},
        {"id":71,"name":"DAV Institute of Management (DAVIM), Faridabad"},
        {"id":72,"name":"DOEACC"},
        {"id":73,"name":"Deen Dayal Upadhyay Gorakhpur University (DDUGU)"},
        {"id":74,"name":"Delhi College of Engineering (DCE), Delhi"},
        {"id":75,"name":"Delhi University - College of Art"},
        {"id":76,"name":"Delhi University - Daulat Ram College"},
        {"id":77,"name":"Delhi University - Hansraj College"},
        {"id":78,"name":"Delhi University - Hindu College"},
        {"id":79,"name":"Delhi University - Lady Shree Ram College (LSR)"},
        {"id":80,"name":"Delhi University - Miranda House"},
        {"id":81,"name":"Delhi University - Ramjas College"},
        {"id":82,"name":"Delhi University - Shri Ram College of Commerce (SRCC)"},
        {"id":83,"name":"Delhi University - Sri Venkateswara College"},
        {"id":84,"name":"Delhi University - St Stephens College"},
        {"id":85,"name":"Delhi University - Other"},
        {"id":86,"name":"Devi Ahilya Vishwa Vidhyalaya (DAVV), Indore"},
        {"id":87,"name":"Dibrugarh University"},
        {"id":88,"name":"Dr. B.R. Ambedkar National Institute of Technology (NIT), Jalandhar"},
        {"id":89,"name":"Dr. Bhim Rao Ambedkar University (BRAU), Bihar"},
        {"id":90,"name":"Dr. Harisingh Gour University (HGU), Sagar"},
        {"id":91,"name":"Dr. MGR Medical University (MGRMU), Chennai"},
        {"id":92,"name":"EMPI Business School"},
        {"id":93,"name":"Elphinstone College, Mumbai"},
        {"id":94,"name":"Faculty Of Management Studies"},
        {"id":95,"name":"Faculty Of Management Studies (FMS), Delhi"},
        {"id":96,"name":"Faculty of Architecture & Ekistics, JMI, Delhi"},
        {"id":97,"name":"Faculty of Law, Aligarh Muslim University, Aligarh"},
        {"id":98,"name":"Fergusson College, Pune"},
        {"id":99,"name":"Film and Television Institute of India (FTII), Pune"},
        {"id":100,"name":"Fore School of Management (FSM), Delhi"},
        {"id":101,"name":"Fortune Institute of International Business (FIIB)"},
        {"id":102,"name":"Gargi College, Delhi"},
        {"id":103,"name":"Goa Institute of Management (GIM)"},
        {"id":104,"name":"Goa University"},
        {"id":105,"name":"Goenka College of Commerce and Business Administration (GCCBA)"},
        {"id":106,"name":"Government College of Engineering (GCE), Pune"},
        {"id":107,"name":"Government College of Science (GCS), Raipur"},
        {"id":108,"name":"Government Medical College and Hospital (GMCH), Chandigarh"},
        {"id":109,"name":"Grant Medical College, Mumbai"},
        {"id":110,"name":"Great Lakes Institute of Management (GLIM)"},
        {"id":111,"name":"Gujarat Agricultural University (GAU)"},
        {"id":112,"name":"Gujarat National Law University, Gandhinagar"},
        {"id":113,"name":"Gujarat University"},
        {"id":114,"name":"Gulbarga University"},
        {"id":115,"name":"Guru Ghasidas University (GGU)"},
        {"id":116,"name":"Guru Gobind Singh Indraprastha University (GGSIU)"},
        {"id":117,"name":"Guru Jambheshwar University of Science and Technology (GJUST), Hisar"},
        {"id":118,"name":"Guru Nanak Dev University (GNDU)"},
        {"id":119,"name":"Gurukula Kangri University (GKU)"},
        {"id":120,"name":"Guwahati Medical College and Hospital (GMCH)"},
        {"id":121,"name":"Guwahati University"},
        {"id":122,"name":"HNB Garhwal University (HNBGU)"},
        {"id":123,"name":"Haldia Institute of Technology (HIT)"},
        {"id":124,"name":"Hidayatullah National Law University (HNLU)"},
        {"id":125,"name":"Himachal Pradesh University (HPU)"},
        {"id":126,"name":"Hyderabad University"},
        {"id":127,"name":"Indian Business Academy (IBA)"},
        {"id":128,"name":"Indian Institute Of Hardware Technology (IIHT)"},
        {"id":129,"name":"Indian Institute Of Packaging (IIP)"},
        {"id":130,"name":"Indian Institute of Bankers (IIB)"},
        {"id":131,"name":"Indian Institute of Finance (IIF)"},
        {"id":132,"name":"Indian Institute of Foreign Trade (IIFT)"},
        {"id":133,"name":"Indian Institute of Hotel Management (IIHM), Aurangabad"},
        {"id":134,"name":"Indian Institute of Management (IIM), Ahmedabad"},
        {"id":135,"name":"Indian Institute of Management (IIM), Bangalore"},
        {"id":136,"name":"Indian Institute of Management (IIM), Indore"},
        {"id":137,"name":"Indian Institute of Management (IIM), Kolkatta"},
        {"id":138,"name":"Indian Institute of Management (IIM), Kozhikode"},
        {"id":139,"name":"Indian Institute of Management (IIM), Lucknow"},
        {"id":140,"name":"Indian Institute of Mass Communication (IIMC), Delhi"},
        {"id":141,"name":"Indian Institute of Materials Management (IIMM)"},
        {"id":142,"name":"Indian Institute of Modern Management (IIMM), Pune"},
        {"id":143,"name":"Indian Institute of Planning And Management (IIPM)"},
        {"id":144,"name":"Indian Institute of Science (IIS), Bangalore"},
        {"id":145,"name":"Indian Institute of Social Welfare and Business Management (IISWBM)"},
        {"id":146,"name":"Indian Institute of Technology (IIT), Bhuvaneshwar"},
        {"id":147,"name":"Indian Institute of Technology (IIT), Chennai"},
        {"id":148,"name":"Indian Institute of Technology (IIT), Delhi"},
        {"id":149,"name":"Indian Institute of Technology (IIT), Gandhinagar"},
        {"id":150,"name":"Indian Institute of Technology (IIT), Guwahati"},
        {"id":151,"name":"Indian Institute of Technology (IIT), Hyderabad"},
        {"id":152,"name":"Indian Institute of Technology (IIT), Indore"},
        {"id":153,"name":"Indian Institute of Technology (IIT), Jodhpur"},
        {"id":154,"name":"Indian Institute of Technology (IIT), Kanpur"},
        {"id":155,"name":"Indian Institute of Technology (IIT), Kharagpur"},
        {"id":156,"name":"Indian Institute of Technology (IIT), Mandi"},
        {"id":157,"name":"Indian Institute of Technology (IIT), Mumbai"},
        {"id":158,"name":"Indian Institute of Technology (IIT), Patna"},
        {"id":159,"name":"Indian Institute of Technology (IIT), Roorkee"},
        {"id":160,"name":"Indian Institute of Technology (IIT), Ropar"},
        {"id":161,"name":"Indian Law Society Law College (ILSLC), Pune"},
        {"id":162,"name":"Indian School of Business (ISB), Hyderabad"},
        {"id":163,"name":"Indian School of Mines (ISM), Dhanbad"},
        {"id":164,"name":"Indian Statistical Institute (ISI), Bangalore"},
        {"id":165,"name":"Indian Statistical Institute (ISI), Delhi"},
        {"id":166,"name":"Indian Statistical Institute (ISI), Kolkatta"},
        {"id":167,"name":"Indira Gandhi National Open University (IGNOU)"},
        {"id":168,"name":"Indraprastha College for Women, Delhi"},
        {"id":169,"name":"Industrial Training Institute (ITI)"},
        {"id":170,"name":"Institute for Technology and Management (ITM)"},
        {"id":171,"name":"Institute of Business Management and Research (IBMR)"},
        {"id":172,"name":"Institute of Chartered Accountant of India (ICAI)"},
        {"id":173,"name":"Institute of Chartered Financial Analysts of India (ICFAI)"},
        {"id":174,"name":"Institute of Company Secretaries of India (ICSI)"},
        {"id":175,"name":"Institute of Cost and Works Accountants of India (ICWAI)"},
        {"id":176,"name":"Institute of Hotel Management (IHM)"},
        {"id":177,"name":"Institute of Hotel Management (IHM), Ahmedabad"},
        {"id":178,"name":"Institute of Hotel Management (IHM), Aurangabad"},
        {"id":179,"name":"Institute of Hotel Management (IHM), Bangalore"},
        {"id":180,"name":"Institute of Hotel Management (IHM), Chennai"},
        {"id":181,"name":"Institute of Hotel Management (IHM), Delhi"},
        {"id":182,"name":"Institute of Hotel Management (IHM), Kolkata"},
        {"id":183,"name":"Institute of Management Education (IME)"},
        {"id":184,"name":"Institute of Management Studies (IMS), Dehradun"},
        {"id":185,"name":"Institute of Management Studies (IMS), Ghaziabad"},
        {"id":186,"name":"Institute of Management Technology (IMT), Ghaziabad"},
        {"id":187,"name":"Institute of Marketing and Management (IMM)"},
        {"id":188,"name":"Institute of Medical Sciences, Varanasi"},
        {"id":189,"name":"Institute of Productivity and Management (IPM)"},
        {"id":190,"name":"Institute of Rural Management (IRMA), Anand"},
        {"id":191,"name":"Institute of Technology, Banaras Hindu University"},
        {"id":192,"name":"International Institute of Information Technology (IIIT), Allahabad"},
        {"id":193,"name":"International Institute of Information Technology (IIIT), Bangalore"},
        {"id":194,"name":"International Institute of Information Technology (IIIT), Hyderabad"},
        {"id":195,"name":"International Institute of Information Technology (IIIT), Kolkatta"},
        {"id":196,"name":"International Management Institute (IMI), Delhi"},
        {"id":197,"name":"International School of Business and Media (ISBM)"},
        {"id":198,"name":"J.D. Birla Institute, Kolkata"},
        {"id":199,"name":"JJ Institute of Applied Art (JJIAA), Mumbai"},
        {"id":200,"name":"Jabalpur University"},
        {"id":201,"name":"Jadavpur University"},
        {"id":202,"name":"Jagan Institute of Management Studies (JIMS)"},
        {"id":203,"name":"Jaipuria Institute of Management (JIMS)"},
        {"id":204,"name":"Jamia Hamdard"},
        {"id":205,"name":"Jamia Milia Islamia (JMI)"},
        {"id":206,"name":"Jammu University"},
        {"id":207,"name":"Jamnalal Bajaj Institute of Management Studies (JLBIM)"},
        {"id":208,"name":"Jawaharlal Nehru Technological University (JNTU)"},
        {"id":209,"name":"Jawaharlal Nehru University (JNU)"},
        {"id":210,"name":"Jesus & Mary College (JMC), Delhi"},
        {"id":211,"name":"Jetking Jipmer,Pondicherry"},
        {"id":212,"name":"Jiwaji University"},
        {"id":213,"name":"K J Somaiya College of Arts & Commerce, Mumbai"},
        {"id":214,"name":"K.J. Somaiya Institute of Management Studies and Research (KJSIMSR), Mumbai"},
        {"id":215,"name":"Kakatiya University"},
        {"id":216,"name":"Kalyani University"},
        {"id":217,"name":"Kannur University"},
        {"id":218,"name":"Kanpur University"},
        {"id":219,"name":"Karnataka State Open University (KSOU)"},
        {"id":220,"name":"Karnataka University"},
        {"id":221,"name":"Karunya University"},
        {"id":222,"name":"Kashmir University"},
        {"id":223,"name":"Kasturba Medical College (KMC), Manipal"},
        {"id":224,"name":"Kerala University"},
        {"id":225,"name":"King Edward Medical College (KEC), Mumbai"},
        {"id":226,"name":"King George Medical College - Chhatrapati Shahuji Maharaj Medical University, Lucknow"},
        {"id":227,"name":"Kota University"},
        {"id":228,"name":"Kumaun University"},
        {"id":229,"name":"Kurukshetra University"},
        {"id":230,"name":"Kuvempu University, Karnataka"},
        {"id":231,"name":"Lady Hardinge Medical College (LHMC), Delhi"},
        {"id":232,"name":"Lal Bahadur Shastri Institute of Management (LBSIM)"},
        {"id":233,"name":"Lovely Professional University (LPU)"},
        {"id":234,"name":"Loyola College, Chennai"},
        {"id":235,"name":"Loyola Institute of Business Administration (LIBM), Chennai"},
        {"id":236,"name":"Lucknow University"},
        {"id":237,"name":"M S Ramaiah Medical College, Bangalore"},
        {"id":238,"name":"MCM DAV College for Women, Chandigarh"},
        {"id":239,"name":"Madan Mohan Malaviya Engineering College (MMMEC)"},
        {"id":240,"name":"Madras Christian College (MCC)"},
        {"id":241,"name":"Madras Medical College (MMC)"},
        {"id":242,"name":"Madras University"},
        {"id":243,"name":"Madurai Kamaraj University (MKU)"},
        {"id":244,"name":"Magadh University"},
        {"id":245,"name":"Maharaja Sayajirao University (MSU), Baroda"},
        {"id":246,"name":"Maharana Pratap University of Agriculture and Technology (MPUAT)"},
        {"id":247,"name":"Maharishi Dayanand Saraswati University (MDSU), Ajmer"},
        {"id":248,"name":"Maharishi Dayanand University (MDU), Rohtak"},
        {"id":249,"name":"Maharishi Institute of Management (MIM)"},
        {"id":250,"name":"Mahatma Gandhi University (MGU)"},
        {"id":251,"name":"Mahatma Jyotiba Phule Rohilkhand University (MJPRS)"},
        {"id":252,"name":"Malviya National Institute of Technology (NIT), Jaipur"},
        {"id":253,"name":"Management Development Institute (MDI), Gurgaon"},
        {"id":254,"name":"Mangalore University"},
        {"id":255,"name":"Manipal Academy of Higher Education (MAHE)"},
        {"id":256,"name":"Manipal Institute of Management (MIM)"},
        {"id":257,"name":"Manipal Institute of Technology (MIT)"},
        {"id":258,"name":"Manipal University"},
        {"id":259,"name":"Manipur University"},
        {"id":260,"name":"Manonmaniam Sundaranar University (MSU), Thirunelvelli"},
        {"id":261,"name":"Maulana Azad Medical College (MAMC), Delhi"},
        {"id":262,"name":"Maulana Azad National Institute of Technology (NIT), Bhopal"},
        {"id":263,"name":"Medical College & Hospital, Kolkata"},
        {"id":264,"name":"Meerut University"},
        {"id":265,"name":"Mithibai Arts Chauhan Institute, Mumbai"},
        {"id":266,"name":"Motilal Nehru Institute National Institute of Technology (NIT), Allahabad"},
        {"id":267,"name":"Mount Carmel College, Bangalore"},
        {"id":268,"name":"Mudra Institute of Communications (MICA), Ahmedabad"},
        {"id":269,"name":"Mumbai University"},
        {"id":270,"name":"NIILM School of Business (NIILSB)"},
        {"id":271,"name":"NIIT"},
        {"id":272,"name":"Nagarjuna University"},
        {"id":273,"name":"Nagpur University"},
        {"id":274,"name":"Narsee Monjee Institute Of Management Studies (NMIMS)"},
        {"id":275,"name":"National Academy of Legal Studies and Research University (NALSAR), Hyderabad"},
        {"id":276,"name":"National Institute of Business Management (NIBM)"},
        {"id":277,"name":"National Institute of Construction Management and Research (NICMR)"},
        {"id":278,"name":"National Institute of Design (NID), Ahmedabad"},
        {"id":279,"name":"National Institute of Design (NID), Bangalore"},
        {"id":280,"name":"National Institute of Engineering (NIE)"},
        {"id":281,"name":"National Institute of Fashion Technology (NIFT)"},
        {"id":282,"name":"National Institute of Fashion Technology (NIFT), Bangalore"},
        {"id":283,"name":"National Institute of Fashion Technology (NIFT), Chennai"},
        {"id":284,"name":"National Institute of Fashion Technology (NIFT), Delhi"},
        {"id":285,"name":"National Institute of Fashion Technology (NIFT), Hyderabad"},
        {"id":286,"name":"National Institute of Fashion Technology (NIFT), Kannur"},
        {"id":287,"name":"National Institute of Fashion Technology (NIFT), Kolkata"},
        {"id":288,"name":"National Institute of Fashion Technology (NIFT), Mumbai"},
        {"id":289,"name":"National Institute of Financial Management (NIFM)"},
        {"id":290,"name":"National Institute of Industrial Engineering (NITIE)"},
        {"id":291,"name":"National Institute of Management (NIM)"},
        {"id":292,"name":"National Institute of Sales (NIS)"},
        {"id":293,"name":"National Institute of Technology,(NIT), Agartala"},
        {"id":294,"name":"National Institute of Technology, (NIT), Arunachal Pradesh"},
        {"id":295,"name":"National Institute of Technology (NIT), Bharatidasan"},
        {"id":296,"name":"National Institute of Technology (NIT), Calicut"},
        {"id":297,"name":"National Institute of Technology,(NIT), Delhi"},
        {"id":298,"name":"National Institute of Technology (NIT), Durgapur"},
        {"id":299,"name":"National Institute of Technology,(NIT), Goa"},
        {"id":300,"name":"National Institute of Technology (NIT), Hamirpur"},
        {"id":301,"name":"National Institute of Technology (NIT), Jamshedpur"},
        {"id":302,"name":"National Institute of Technology (NIT), Karnataka"},
        {"id":303,"name":"National Institute of Technology (NIT), Kurukshetra"},
        {"id":304,"name":"National Institute of Technology,(NIT), Manipur"},
        {"id":305,"name":"National Institute of Technology,(NIT), Mizoram"},
        {"id":306,"name":"National Institute of Technology,(NIT), Meghalaya"},
        {"id":307,"name":"National Institute of Technology, (NIT), Nagaland"},
        {"id":308,"name":"National Institute of Technology (NIT), Patna"},
        {"id":309,"name":"National Institute of Technology (NIT), Raipur"},
        {"id":310,"name":"National Institute of Technology (NIT), Rourkela"},
        {"id":311,"name":"National Institute of Technology, (NIT), Sikkim"},
        {"id":312,"name":"National Institute of Technology (NIT), Silchar"},
        {"id":313,"name":"National Institute of Technology (NIT), Srinagar"},
        {"id":314,"name":"National Institute of Technology (NIT), Suratkal"},
        {"id":315,"name":"National Institute of Technology (NIT), Tiruchirappalli"},
        {"id":316,"name":"National Institute of Technology (NIT), Warangal"},
        {"id":317,"name":"National Institute of Technology (NIT), Other"},
        {"id":318,"name":"National Law Institute University (NLIU), Bhopal"},
        {"id":319,"name":"National Law School of India University (NLSIU), Bangalore"},
        {"id":320,"name":"National Law University (NLU), Jodhpur"},
        {"id":321,"name":"National Power Training Institute (NPTI)"},
        {"id":322,"name":"Netaji Subhas Institute of Technology (NSIT)"},
        {"id":323,"name":"Nettur Technical Training Foundation (NTTF)"},
        {"id":324,"name":"New Delhi Institute of Management (NDIM)"},
        {"id":325,"name":"Nilratan Sircar Medical College, Kolkata"},
        {"id":326,"name":"Nirma Institute of Management (NIM), Ahmedabad"},
        {"id":327,"name":"North Bengal University (NBU)"},
        {"id":328,"name":"North Eastern Hill University (NEHU)"},
        {"id":329,"name":"North Gujarat University (NGU)"},
        {"id":330,"name":"North Maharashtra University (NMU)"},
        {"id":331,"name":"North Orissa University (NOU)"},
        {"id":332,"name":"Northern India Institute of Fashion Technology (NIIFT), Mohali"},
        {"id":333,"name":"Oberoi Centre for Learning and Development (OCLD)"},
        {"id":334,"name":"Osmania Medical College, Hyderabad"},
        {"id":335,"name":"Osmania University"},
        {"id":336,"name":"PSG, Coimbatore"},
        {"id":337,"name":"Panjab University"},
        {"id":338,"name":"Patna University"},
        {"id":339,"name":"Pearl Academy, Delhi"},
        {"id":340,"name":"Periyar University"},
        {"id":341,"name":"Pondicherry University"},
        {"id":342,"name":"Pragathi Mahavidyalaya, Hyderabad"},
        {"id":343,"name":"Presidency College, Chennai"},
        {"id":344,"name":"Presidency College, Kolkatta"},
        {"id":345,"name":"Pune University"},
        {"id":346,"name":"Punjab Engineering College (PEC)"},
        {"id":347,"name":"Punjab Technical University (PTU)"},
        {"id":348,"name":"Punjabi University, Patiala"},
        {"id":349,"name":"R.A. Podar College of Commerce and Economics, Mumbai"},
        {"id":350,"name":"RV College Of Engineering (RVCE)"},
        {"id":351,"name":"Rai Business School (RBS)"},
        {"id":352,"name":"Rai University"},
        {"id":353,"name":"Rajasthan University"},
        {"id":354,"name":"Rajiv Gandhi Proudyogiki Vishwavidyalaya (RGPV), Bhopal"},
        {"id":355,"name":"Ranchi University"},
        {"id":356,"name":"Rani Birla Girls College, Kolkata"},
        {"id":357,"name":"Rani Durgavati Vishwavidyalaya (RDVV), Jabalpur"},
        {"id":358,"name":"SIES College of Management Studies (SIESCMS)"},
        {"id":359,"name":"SP Jain Institute of Management Research (SPJIMR), Mumbai"},
        {"id":360,"name":"SRM university (SRMU)"},
        {"id":361,"name":"Sambalpur University"},
        {"id":362,"name":"Sardar Patel University (SPU)"},
        {"id":363,"name":"Sardar Vallabhbhai National Institute of Technology (NIT), Surat"},
        {"id":364,"name":"Sastra University"},
        {"id":365,"name":"Sathyabama University"},
        {"id":366,"name":"Saurashtra University"},
        {"id":367,"name":"School Of Planning and Architecture (SPA)"},
        {"id":368,"name":"Seth Gordhandas Sunderdas Medical College, Mumbai"},
        {"id":369,"name":"Shivaji University, Maharasthra"},
        {"id":370,"name":"Shreemati Nathibai Damodar Thackersey Womens University (SNDTWU)"},
        {"id":371,"name":"Shri Bhagawan Mahaveer Jain College, Bangalore"},
        {"id":372,"name":"Shri Narsee Monjee College of Commerce and Economics, Mumbai"},
        {"id":373,"name":"Siddaganga Institute of Technology (SIT)"},
        {"id":374,"name":"Sikkim Manipal University (SMU)"},
        {"id":375,"name":"Siliguri Institute Of Technology (SIT)"},
        {"id":376,"name":"Sir J J College of Architecture, Mumbai"},
        {"id":377,"name":"Sophia College for Women, Mumbai"},
        {"id":378,"name":"Sri Guru Gobind Singh College of Commerce, Delhi"},
        {"id":379,"name":"Sri Jayachamarajendran College of Engineering (SJCE)"},
        {"id":380,"name":"Sri Krishnadevaraya University (SKU)"},
        {"id":381,"name":"Sri Ramachandra Medical College & Research Institute, Chennai"},
        {"id":382,"name":"Sri Venkateshwara University (SVU), Tirupati"},
        {"id":383,"name":"St. Johns Medical College, Bangalore"},
        {"id":384,"name":"St.Josephs College, Bangalore"},
        {"id":385,"name":"St.Xaviers College, Ahmedabad"},
        {"id":386,"name":"St.Xaviers College, Kolkatta"},
        {"id":387,"name":"St.Xaviers College, Mumbai"},
        {"id":388,"name":"Stanley Medical College (SMC), Chennai"},
        {"id":389,"name":"State Institute of Education Technology (SIET), Lucknow"},
        {"id":390,"name":"State Institute of Education Technology (SIET), Patna"},
        {"id":391,"name":"State Institute of Education Technology (SIET), Pune"},
        {"id":392,"name":"State Institute of Education Technology (SIET), Thiruvananthapuram"},
        {"id":393,"name":"Stella Maris College (SMC), Chennai"},
        {"id":394,"name":"Sushant School of Art and Architecture, Gurgaon"},
        {"id":395,"name":"Swami Ramanand Teerth Marathawada University (SRTMU)"},
        {"id":396,"name":"Symbiosis Centre For Management and HRD (SCMHRD)"},
        {"id":397,"name":"Symbiosis Centre for Distance Learning (SCDL)"},
        {"id":398,"name":"Symbiosis Institute of Business Management (SIBM), Pune"},
        {"id":399,"name":"Symbiosis Institute of Management Studies (SIMS)"},
        {"id":400,"name":"Symbiosis Society Law College (SSLC), Pune"},
        {"id":401,"name":"Symbiosis Societys College of Arts & Commerce, Pune"},
        {"id":402,"name":"Symbiosis, Pune"},
        {"id":403,"name":"TASMAC"},
        {"id":404,"name":"Ta Pai Management Institute (TAPMI)"},
        {"id":405,"name":"Tamil Nadu Open University (TNOU)"},
        {"id":406,"name":"Tata Institute of Social Sciences (TISS)"},
        {"id":407,"name":"Tezpur University"},
        {"id":408,"name":"Thapar Institute of Engineering and Technology (TIET)"},
        {"id":409,"name":"The Institute of Post Graduate Medical Education & Research (IPGMER), Kolkata"},
        {"id":410,"name":"The Oxford College of Science, Bangalore"},
        {"id":411,"name":"The W.B. National University of Juridical Sciences(NUJS), Kolkata"},
        {"id":412,"name":"Thiruvalluvar University"},
        {"id":413,"name":"Tripura University"},
        {"id":414,"name":"University Business School (UBS), Chandigarh"},
        {"id":415,"name":"University College of Law (UCL), Bangalore"},
        {"id":416,"name":"University College of Medical Sciences & GTB Hospital, Delhi"},
        {"id":417,"name":"University Vishveshvaraya College of Engineering (UVCE)"},
        {"id":418,"name":"University of Mysore"},
        {"id":419,"name":"University of North Bengal (UNB)"},
        {"id":420,"name":"University of Petroleum and Energy Studies, Dehradun"},
        {"id":421,"name":"Utkal University"},
        {"id":422,"name":"Uttar Pradesh Technical University (UPTU)"},
        {"id":423,"name":"Veer Bahadur Singh Purvanchal University (VBSPU)"},
        {"id":424,"name":"Veer Narmad South Gujarat University (VNSGU)"},
        {"id":425,"name":"Vellore Engineering College (VEC)"},
        {"id":426,"name":"Vellore Institute of Technology (VIT)"},
        {"id":427,"name":"Vidyasagar University"},
        {"id":428,"name":"Vikram University, Ujjain"},
        {"id":429,"name":"Vinayaka Mission University (VMU)"},
        {"id":430,"name":"Vinoba Bhave University (VBU)"},
        {"id":431,"name":"Visvesvaraya National Institute of Technology (NIT), Nagpur"},
        {"id":432,"name":"Visveswaraiah Technological University (VTU)"},
        {"id":433,"name":"Welcomgroup Graduate School of Hotel Administration (WGSHA), Manipal"},
        {"id":434,"name":"Welingkar Institute of Management Development and Research (WIMDR)"},
        {"id":435,"name":"West Bengal University of Technology (WBUT)"},
        {"id":436,"name":"Wigan and Leigh College (WLC)"},
        {"id":437,"name":"Wildlife Institute of India (WII)"},
        {"id":438,"name":"Xavier Institute of Social Service (XISS), Ranchi"},
        {"id":439,"name":"Xavier Labour Relations Institute (XLRI), Jamshedpur"},
        {"id":440,"name":"Xaviers Institute of Management (XIMS), Bhuvaneshwar"},
        {"id":441,"name":"Yashwantrao Chavan Maharashtra Open University (YCMOU)"},
        {"id":442,"name":"Young Men Christian Association (YMCA)"},
        {"id":443,"name":"Young Womens Christian Association (YWCA)"},
        {"id":444,"name":"Others"},

    ]
}